name: Configure CI
description: Performs the initial configuration of the CI environment

inputs:
  java:
    description: The Java version to use
    required: false
    default: 8.0.382-tem
  gradle:
    description: The Gradle version to use
    required: false
    default: 6.7.1
  kotlin:
    description: The Kotlin version to use
    required: false
    default: 1.6.21

runs:
  using: composite

  steps:
    - run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk list java
        sdk install java $JAVA && sdk default java $JAVA
        sdk install gradle $GRADLE && sdk default gradle $GRADLE
        sdk install kotlin $KOTLIN && sdk default kotlin $KOTLIN
      shell: bash
      env:
        JAVA: ${{ inputs.java }}
        GRADLE: ${{ inputs.gradle }}
        KOTLIN: ${{ inputs.kotlin }}

    - run: ./gradlew androidDependencies
      shell: bash

    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0
