version: 2
jobs:
  build:
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/android:api-28

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ checksum  "lib/build.gradle" }}
    - run: ./gradlew androidDependencies
    - save_cache:
        key: v1-dep-{{ checksum  "lib/build.gradle" }}
        paths:
        - ~/.gradle
        - ~/.android
        - /usr/local/android-sdk-linux/extras
    - run:
        name: Run checks
        command: ./gradlew clean test lint --continue --console=plain --max-workers=4
    - store_artifacts:
        path: lib/build/reports
        destination: reports
    - store_test_results:
        path: lib/build/test-results